name: Minha primeira Pipeline
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello Work Rodrigo Afonso"
      
      - name: "Minha segunda ação"
        run: |
          echo "Rodrigo Afonso, você criou sua primeira ação"
          echo "Parabéns!!! Rodrigo Afonso, KI TOP!!! KIKITOP"
      
      # Executando um script Python
      - name: "Executando um Script em Python"
        run: |
          variavel = "Escrevendo com Python"
          print(variavel)
        shell: python
  
  segundo-job:
    name: "Instalação do Ambiente NodeJs"
    runs-on: ubuntu-latest
    steps:
      - name: "Vericando a versão do NodeJs atual"
        run: node --version
      - name: "Definição da Versão da versão 20.17.0 NodeJs"
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - name: "Vericando a versão do NodeJs após Setup"
        run: node --version


  
